services:
  mongodb:
      image: mongo
      restart: always
      environment:
        MONGO_INITDB_ROOT_USERNAME: docker
        MONGO_INITDB_ROOT_PASSWORD: dockerpwd
      ports:
        - 27017:27017
  app:
    build: .
    image: nodejs_lts_iron:latest
    restart: always
    environment: 
      NODE_ENV: development
    tty: true
    ports:
      - "3333:3333"
    depends_on:
      - mongodb